### Simple Get
GET  http://localhost:3000/food HTTP/1.1
Accept: application/json

### Simple Post
POST http://localhost:3000/food HTTP/1.1
content-type: application/json

{
    "id": 0,
    "name": "Hamburger",
    "price": 9,
    "calories": 1200
}