### Get Skills
GET http://localhost:5000/api/skills


### Send skills
POST http://localhost:5000/api/skills
content-type: application/json

{
    "name": "REST CLient",
    "hours": 4,
    "completed": true,
    "dueDate": "2021-11-15T13:45:02.8672089"
}