# Build Image
FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /build

COPY . .
RUN dotnet restore "securing-api.csproj"
RUN dotnet publish -c Release -o /app

# Runtime Image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app .
ENTRYPOINT ["dotnet", "securing-api.dll"]

# Build Image
# docker build --rm -f dockerfile -t securing-api .
# docker run -it --rm -p 5051:80 securing-api

# docker tag securing-api arambazamba/securing-api
# docker push arambazamba/securing-api

# Injecting environment variables into the container
# docker run -it --rm -p 5051:80 securing-api -e "UseFirebaseAuth"="true" -e "FirebaseProjectId"="fbauth-c3b69" 

# Browse using: 
# http://localhost:5051
# http://localhost:5051/food
# http://localhost:5051/env